import type { Metadata } from 'next'
import './globals.css'
import { NoiseBackground } from '@/components/noise-background'
import { Header } from '@/components/header'
import { inter, firaMono } from '@/styles/font'
import '@/lib/dayjs'

export const metadata: Metadata = {
	title: 'dicebugging',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body
				className={`${inter.variable} ${firaMono.variable} relative font-sans min-h-dvh text-foreground bg-background before:absolute before:inset-0 before:content-[''] before:min-h-dvh before:min-w-full before:noise before:opacity-20 before:-z-10`}
			>
				<Header />

				{children}
				<NoiseBackground />
			</body>
		</html>
	)
}
