import type { Metadata } from 'next'
import './globals.css'
import { NoiseBackground } from '@/components/noise-background'
import { inter, firaMono } from '@/styles/font'

export const metadata: Metadata = {
	title: 'dicebugging',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body
				className={`${inter.variable} ${firaMono.variable} font-sans min-h-dvh text-foreground bg-background before:absolute before:content-[''] before:inset-0 before:min-h-full before:min-w-full before:noise before:bg-background before:opacity-10 before:-z-10`}
			>
				{children}
				<NoiseBackground />
			</body>
		</html>
	)
}
